### ISSUE TITLE
error on requirements.txt

### ISSUE THREAD

**Issue by AlvaroHermida** [BarnabyShearer/efm8#1]
The second line of https://github.com/BarnabyShearer/efm8/blob/master/requirements.txt says:
PyCRC>=1.21
but the current version of pycrc is 0.9.2
https://pypi.org/project/pycrc/#history

the line may be a wrong reference to pythoncrc 1.21
https://pypi.org/project/pythoncrc/#history

**Comment by BarnabyShearer** [comment]
Sorry for the delay in investigating. This is odd the certainly was a PyCRC 1.21 here https://github.com/alexbutirskiy/PyCRC/blob/master/setup.py. Looks like `pythoncrc` is the same code published by a different maintainer. I will switch to that for now.
